import Link from "next/link"
import { ShieldCheck } from "lucide-react"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-border">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <ShieldCheck className="h-6 w-6 text-brand-teal" />
            <span className="text-lg font-bold text-brand-navy">Cyber Trust Nest</span>
          </Link>
          <Link href="/" className="text-sm text-brand-teal hover:underline">
            Back to home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold text-brand-navy mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">
          Last updated: September 16, 2026
        </p>

        <div className="prose prose-gray max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              By accessing or using Cyber Trust Nest (the &quot;Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">2. Description of Service</h2>
            <p className="text-gray-600 leading-relaxed">
              Cyber Trust Nest provides compliance guidance to small and medium-sized businesses. The Service helps organizations understand which regulations, frameworks, and certifications apply to them, and provides actionable recommendations, policy templates, and deadline tracking.
            </p>
            <p className="text-gray-600 leading-relaxed mt-3">
              <strong>The Service is not a law firm and does not provide legal advice.</strong> All guidance is based on published regulations and frameworks, and every recommendation includes citations to the original source.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">3. Not Legal Advice</h2>
            <p className="text-gray-600 leading-relaxed">
              The compliance profiles, action plans, policy templates, and other outputs generated by Cyber Trust Nest are for informational and educational purposes only. They do not constitute legal, regulatory, or professional compliance advice.
            </p>
            <p className="text-gray-600 leading-relaxed mt-3">
              You should always consult with qualified legal counsel or a licensed Data Protection Compliance Organization (DPCO) before filing regulatory documents, making compliance decisions, or relying on any guidance provided by the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">4. Account Registration</h2>
            <ul className="list-disc list-inside text-gray-600 space-y-1 ml-4">
              <li>You must provide accurate and complete information during registration.</li>
              <li>You are responsible for maintaining the confidentiality of your account.</li>
              <li>You must be at least 18 years old to use the Service.</li>
              <li>One person or entity may not maintain more than one free account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">5. Subscriptions and Payments</h2>
            <ul className="list-disc list-inside text-gray-600 space-y-2 ml-4">
              <li><strong>Free tier:</strong> Limited to 1 compliance profile, 3 deadlines, and newsletter access.</li>
              <li><strong>Pro tier:</strong> Billed monthly or annually in Nigerian Naira (NGN) or US Dollars (USD). Prices are displayed on the pricing page and may change with 30 days&apos; notice.</li>
              <li><strong>Cancellation:</strong> You may cancel your subscription at any time. Access continues until the end of the current billing period.</li>
              <li><strong>Refunds:</strong> Annual subscriptions are refundable within 14 days of purchase. Monthly subscriptions are non-refundable.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">6. User Content</h2>
            <p className="text-gray-600 leading-relaxed">
              You retain ownership of all data you input into the Service. By using the Service, you grant us a limited license to process your data for the purpose of providing the Service (generating compliance profiles, reminders, etc.).
            </p>
            <p className="text-gray-600 leading-relaxed mt-3">
              You are responsible for the accuracy of the information you provide. The quality of compliance guidance depends on the accuracy of your inputs.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">7. Acceptable Use</h2>
            <p className="text-gray-600 leading-relaxed">You agree not to:</p>
            <ul className="list-disc list-inside text-gray-600 space-y-1 ml-4 mt-2">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to other accounts or systems</li>
              <li>Reverse engineer or extract the underlying rules engine or regulation library</li>
              <li>Use the Service to send phishing simulations without proper authorization and consent</li>
              <li>Resell or redistribute compliance profiles without proper licensing</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">8. Intellectual Property</h2>
            <p className="text-gray-600 leading-relaxed">
              The Service, including its design, code, regulation mappings, policy templates, and branding, is owned by Cyber Trust Nest. Policy templates are licensed to you for use within your organization. You may not redistribute templates externally.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">9. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              To the maximum extent permitted by law, Cyber Trust Nest shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to fines, penalties, or losses resulting from:
            </p>
            <ul className="list-disc list-inside text-gray-600 space-y-1 ml-4 mt-2">
              <li>Your reliance on guidance provided by the Service</li>
              <li>Inaccurate information you provided to the Service</li>
              <li>Regulatory changes that have not yet been incorporated</li>
              <li>Failure to consult with qualified legal or compliance professionals</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">10. Termination</h2>
            <p className="text-gray-600 leading-relaxed">
              We may suspend or terminate your access to the Service at any time for violation of these Terms. Upon termination, your right to use the Service ceases. You may request export of your data within 30 days of termination.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">11. Governing Law</h2>
            <p className="text-gray-600 leading-relaxed">
              These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved in the courts of Lagos State, Nigeria.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">12. Changes to These Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              We may revise these Terms from time to time. We will notify you of material changes via email or in-app notification. Continued use of the Service after changes constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-brand-navy mb-3">13. Contact</h2>
            <p className="text-gray-600 leading-relaxed">
              Questions about these Terms? Contact us at:
            </p>
            <p className="text-gray-600 mt-2">
              Email: legal@cybertrustnest.com
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
